BC3/Controllers/UuDaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using BC3.Services;

namespace BC3.Controllers
{
    public class UuDaiController : Controller
    {
        private readonly UuDaiService _uuDaiService;

        public UuDaiController()
        {
            var neo4jService = new Neo4jService();
            _uuDaiService = new UuDaiService(neo4jService);
        }

        // GET: UuDai
        public async Task<ActionResult> UuDaiPartial()
        {
            var vouchers = await _uuDaiService.GetAllVoucherAsync();
            return View(vouchers);
        }

        // Chi tiết ưu đãi
        public async Task<ActionResult> DetailUD(string id)
        {
            var voucher = await _uuDaiService.GetUuDaiByIDAsync(id);
            var allVouchers = await _uuDaiService.GetAllVoucherAsync();
            // Chuyển dữ liệu đến View dưới dạng Tuple
            var model = Tuple.Create(voucher, allVouchers);
            return View(model);
        }
    }
}

BC3/Views/UuDai/DetailUD.cshtml
@model Tuple<BC3.Classes.UuDai, List<BC3.Classes.UuDai>>

@{
    ViewBag.Title = "DetailUD";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string ngayS = String.Format("{0:dd/MM/yyyy}", Model.Item1.DayStart);
    string ngayE = String.Format("{0:dd/MM/yyyy}", Model.Item1.DayEnd);
}

<div class="row">
    <div class="col-8">
        <h1 class="text-uppercase" style="color:firebrick; font-weight:900">Ưu đãi @Model.Item1.TenUD</h1>
        <div class="row mb-3">
            <div class="col-6">
                <span class="bg-warning rounded-3 px-2 py-2 text-black"><i class="bi bi-calendar-event"></i> Thời gian diễn ra: @ngayS - @ngayE</span>
            </div>
            <div class="col-3"></div>
            <div class="col-3 float-end">
                @if (Model.Item1.TrangThai_UD == 1)
                {
                    <span class="bg-primary rounded-3 text-end px-3 py-2">Ưu đãi</span>
                }
                else
                {
                    <span class="bg-danger rounded-3 text-end px-3 py-2">Hết ưu đãi</span>
                }
            </div>
        </div>
        <p>
            @Model.Item1.TomTat_UD <br />
            @Model.Item1.NoiDung_UD
        </p>
        <img class="img-fluid w-50 rounded-3 mx-auto d-block" src="~/Image/uudai/@Model.Item1.Hinh_UD" />
    </div>
    <div class="col-4 bg-dark bg-opacity-75 rounded-3">
        @Html.Partial("UDLQ", Model.Item2) <!-- Gọi partial view để hiển thị các ưu đãi còn lại -->
    </div>
</div>

BC3/Views/UuDai/UDLQ.cshtml
@model List<BC3.Classes.UuDai>

@{
    ViewBag.Title = "UDLQ";
    Layout = null;
    string id = TempData["UD"]?.ToString();
    int a = 0;
}

<div class="row mt-2">
    @if (Model != null && Model.Any())
    {
        foreach (var item in Model)
        {
            if (a == 0)
            {
                <h3 class="text-uppercase text-end" style="font-weight:800; color: darkorange;">Ưu đãi khác</h3>
                a = 1;
            }

            if (item.MaUD != id) // Kiểm tra để không hiển thị ưu đãi hiện tại
            {
                <div class="row mt-3">
                    <div class="col-5">
                        <a href="@Url.Action("DetailUD", "UuDai", new { id = item.MaUD })">
                            <img src="~/Image/uudai/@item.Hinh_UD" class="img-fluid" />
                        </a>
                    </div>
                    <div class="col-7 ">
                        <a href="@Url.Action("DetailUD", "UuDai", new { id = item.MaUD })" class="text-decoration-none text-white">
                            <h5 class="text-uppercase">@item.TenUD</h5>
                        </a>
                        <p class="text-secondary">@item.TomTat_UD</p>
                        <a href="@Url.Action("DetailUD", "UuDai", new { id = item.MaUD })" class="btn btn-outline-warning">Xem chi tiết</a>
                    </div>
                </div>
                <hr />
            }
        }
    }
</div>

BC3/Views/UuDai/UuDaiPartial.cshtml
@model List<BC3.Classes.UuDai>

@{
    ViewBag.Title = "UuDaiPartial";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .backup {
        background-image: url("../Image/back/buu.jpg");
        width: 100%;
        height: 20%;
        opacity: 0.8;
    }
</style>

<div class="backup d-block mx-auto">
    <br />
    <br />
    <br />
    <br />
    <h1 class="text-uppercase text-center text-black text-bg-warning p-2" style="font-weight:900; font-size:60px">Ưu đãi</h1>
    <br />
    <br />
    <br />
    <br />
</div>

<div class="row mt-4">
    @foreach (var item in Model)
    {
    <div class="col-4 mt-3 ">
        <div class="card bg-black text-center h-100">
            <div class="card-img-top">
                <img class="img-fluid rounded-3" src="~/Image/uudai/@item.Hinh_UD" />
            </div>
            <div class="card-body">
                <div class="card-text text-white">
                    <h5>COMBO @item.TenUD</h5>
                    <p>@item.TomTat_UD</p>
                </div>
                <a href="@Url.Action("DetailUD", "UuDai", new { id = item.MaUD })" class="btn btn-outline-warning px-5 mt-2">Xem chi tiết</a>
            </div>
        </div>
    </div>
    }
</div>