BC3/Controllers/TinTucController.cs
using BC3.Classes;
using BC3.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BC3.Controllers
{
    public class TinTucController : Controller
    {
        private readonly TinTucService _tinTucService;

        public TinTucController()
        {
            var neo4jService = new Neo4jService();
            _tinTucService = new TinTucService(neo4jService);
        }

        // GET: TinTuc
        public async Task<ActionResult> TinTucPartial()
        {
            var news = await _tinTucService.GetAllNewsAsync();
            return View(news);
        }

        // Chi tiết tin tức
        public async Task<ActionResult> DetailTin(string id)
        {
            var news = await _tinTucService.GetTinTucByIDAsync(id);
            if (news == null)
            {
                return RedirectToAction("ErrorPage", "Home");
            }

            // Lưu id tin tức vào TempData để sử dụng ở view khác
            TempData["TT"] = news.MaTT;

            var relatedNews = await _tinTucService.GetAllNewsAsync();

            var model = new Tuple<TinTuc, List<TinTuc>>(news, relatedNews);
            return View(model);
        }

        public async Task<ActionResult> TinLQ()
        {
            var news = await _tinTucService.GetAllNewsAsync();
            return PartialView(news);
        }
    }
}

BC3/Views/TinTuc/DetailTin.cshtml
@model Tuple<BC3.Classes.TinTuc, List<BC3.Classes.TinTuc>>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string ngay = String.Format("{0:dd/MM/yyyy}", Model.Item1.DayShow);
}

<h1 class="text-uppercase text-center" style="color:firebrick; font-weight:900">@Model.Item1.TenTT</h1>
<div class="row">
    <div class="col-6">
        <span class="bg-warning rounded-3 px-3 text-black"><i class="bi bi-calendar-event"></i> @ngay</span>
    </div>
    <div class="col-4"></div>
    <div class="col-2 float-end">
        @if (Model.Item1.TrangThai_TT == 1)
        {
        <span class="bg-primary rounded-3 text-end px-3">Chưa diễn ra</span>
        }
        else
        {
        <span class="bg-danger rounded-3 text-end px-3">Đã diễn ra</span>
        }
    </div>
</div>

<p class="px-5" style="font-size:18px">
    <strong style="font-size:22px">@Model.Item1.TenTT</strong><br />
    &nbsp;&nbsp;&nbsp;@Model.Item1.TomTat_TT.
</p>
<img class="img-fluid w-50 rounded-3 mx-auto d-block" src="~/Image/tintuc/@Model.Item1.Hinh_TT" />
<br />
&nbsp;&nbsp;&nbsp;@Model.Item1.NoiDung_TT
<br />

<div class="align-items-center mt-3">
    @Html.Partial("TinLQ", Model.Item2)
</div>

BC3/Views/TinTuc/TinLQ.cshtml
@model List<BC3.Classes.TinTuc>

@{
    Layout = null;
    string currentId = TempData["TT"]?.ToString();
}

<div class="row mt-2">
    @if (Model != null && Model.Any())
    {
    <h1 class="text-uppercase text-center">Tin tức khác</h1>
        foreach (var item in Model)
        {
            if (item.MaTT != currentId) // Chỉ hiển thị các tin tức khác
            {
    <div class="col-4 mt-3 mx-auto">
        <div class="card bg-warning bg-opacity-25 text-center h-100 rounded-3">
            <div class="card-img-top">
                <img class="img-fluid" style="width:400px; height:300px" src="~/Image/tintuc/@item.Hinh_TT" />
            </div>
            <div class="card-body">
                <div class="card-text">
                    <h5 class="text-white">@item.TenTT</h5>
                    <p class="text-white-50">@item.TomTat_TT</p>
                </div>
                <a href="@Url.Action("DetailTin", "TinTuc", new { id = item.MaTT })" class="btn btn-outline-warning mt-2">Xem chi tiết</a>
            </div>
        </div>
    </div>
            }
        }
    }
    else
    {
    <p>Không có tin tức liên quan.</p>
    }
</div>

BC3/Views/TinTuc/TinTucPartial.cshtml
@model List<BC3.Classes.TinTuc>

@{
    ViewBag.Title = "TinTucPartial";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .backup {
        background-image: url("../Image/back/buu.jpg");
        width: 100%;
        height: 20%;
        opacity: 0.8;
    }
</style>

<div class="backup d-block mx-auto">
    <br />
    <br />
    <br />
    <br />
    <h1 class="text-uppercase text-center text-black text-bg-warning p-2" style="font-weight:900; font-size:60px">Tin tức</h1>
    <br />
    <br />
    <br />
    <br />
</div>

<div class="row mt-4">
    @if (Model != null && Model.Any())
    {
        // Lấy tin đầu tiên
        var firstItem = Model.First();
    <div class="col-5">
        <a href="@Url.Action("DetailTin", "TinTuc", new { id = firstItem.MaTT })">
            <img src="~/Image/tintuc/@firstItem.Hinh_TT" class="img-fluid w-100 h-75 rounded-3" />
        </a>
        <a href="@Url.Action("DetailTin", "TinTuc", new { id = firstItem.MaTT })" class="text-decoration-none text-warning">
            <h3 class="text-uppercase text-center">@firstItem.TenTT</h3>
        </a>
        <p class="text-secondary">@firstItem.TomTat_TT</p>
        <a href="@Url.Action("DetailTin", "TinTuc", new { id = firstItem.MaTT })" class="btn btn-outline-warning">Xem chi tiết</a>
    </div>

    <div class="col-7">
        @foreach (var item in Model.Skip(1)) // Bỏ qua tin đầu tiên
            {
        <div class="row mt-5">
            <div class="col-4">
                <a href="@Url.Action("DetailTin", "TinTuc", new { id = item.MaTT })">
                    <img src="~/Image/tintuc/@item.Hinh_TT" class="img-fluid w-100 rounded-3" />
                </a>
            </div>
            <div class="col-8">
                <a href="@Url.Action("DetailTin", "TinTuc", new { id = item.MaTT })" class="text-decoration-none text-white">
                    <h5 class="text-uppercase">@item.TenTT</h5>
                </a>
                <p class="text-secondary">@item.TomTat_TT</p>
            </div>
        </div>
            }
    </div>
    }
</div>